modLoader = "javafml"
loaderVersion = "[1,)"
license = "XDs-MC-License"
issueTrackerURL = "https://github.com/XDPXI/XDs-Mod-Template/issues"
showAsResourcePack = false

[[mods]]
modId = "template"
namespace = "template"
version = "1.0.0"
displayName = "XD's Mod Template"
description = "A multi version and loader template for creating minecraft mods."
logoFile = "assets/template/icon.png"
authors = "XDPXI"
displayURL = "https://github.com/XDPXI/XDs-Mod-Template"

[[dependencies.template]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.6,1.21.8]"
ordering = "NONE"
side = "BOTH"

[[dependencies.template]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
